### ISSUE TITLE
When the topmost and a leaf module share a name, we get an error.

### ISSUE THREAD

**Issue by Drvi** [Drvi/ProtocolBuffers.jl#16]
So while making the change to preserve package names exactly without making them more “julian”*, I also deleted the code that made the individual module names unique. Now there is this edge case, when if the leaf module has the same name as to topmost module, you can’t import it because the names would clash (and we have to import it to namespace imported definitions).

There is this vector database, [Milvus](https://github.com/milvus-io/milvus), which provides a ProtoBuf interface. The current ProtoBuf [doesn’t handle it for some reason related to scope resolution](https://github.com/JuliaIO/ProtoBuf.jl/issues/200), we do generate code that is valid except for one thing: there is a `milvus.proto.milvus` package used by this file which tried to import the topmost `milvus` module into the leaf `milvus` module so that we can reach stuff in `milvus.proto.common` module. To solve this, I propose:

When importing the topmost module, if the names clash, use an alias for it (i.e. `import ...milvus`  -> `import ...milvus as var"#milvus"`) and make sure that when fully qualifying imported names, we use the alias.

\* We want to do this so that parsing fully qualified names from `Any` types has less runtime overhead.

Sounds good, @quinnj?

**Comment by quinnj** [comment]
Yeah, that sounds like a good solution to me
